In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

corpus = [
    "PersonA likes icecream",
    "PersonB hates icecream",
    "PersonC likes icecream and coffee",
    "PersonD hates icecream and coffee"
]

In [13]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk

stopwords_list = list(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()


In [22]:
word_list = []
for sent in corpus:
    words = nltk.word_tokenize(sent)
    word_temp = []
    for word in words:
        if word not in stopwords_list:
            word_temp.append(lemmatizer.lemmatize(word))
    word_list.append((' ').join(word_temp))
    # print(lemmatizer.lemmatize(sent))
# print(word_list)


In [21]:
cv = CountVectorizer(max_features=500, ngram_range=(1,2))
X = cv.fit_transform(word_list)
feature_names =  cv.get_feature_names_out()
print(X.toarray())
print("Feature names:", feature_names)
print("Vocabulary", cv.vocabulary_)

[[0 0 0 1 0 1 1 1 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1 0 0 0 0]
 [1 0 0 1 1 1 1 0 0 0 0 1 1 0 0]
 [1 1 1 1 1 0 0 0 0 0 0 0 0 1 1]]
Feature names: ['coffee' 'hate' 'hate icecream' 'icecream' 'icecream coffee' 'like'
 'like icecream' 'persona' 'persona like' 'personb' 'personb hate'
 'personc' 'personc like' 'persond' 'persond hate']
Vocabulary {'persona': 7, 'like': 5, 'icecream': 3, 'persona like': 8, 'like icecream': 6, 'personb': 9, 'hate': 1, 'personb hate': 10, 'hate icecream': 2, 'personc': 11, 'coffee': 0, 'personc like': 12, 'icecream coffee': 4, 'persond': 13, 'persond hate': 14}


In [19]:
word_counts = np.sum(X.toarray(), axis=0)
freq_words = dict(zip(feature_names, word_counts))
freq_words

{'coffee': 2,
 'hate': 2,
 'hate icecream': 2,
 'icecream': 4,
 'icecream coffee': 2,
 'like': 2,
 'like icecream': 2,
 'persona': 1,
 'persona like': 1,
 'personb': 1,
 'personb hate': 1,
 'personc': 1,
 'personc like': 1,
 'persond': 1,
 'persond hate': 1}

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer 

tfidf = TfidfVectorizer(max_features=500, ngram_range=(1,2))
X = tfidf.fit_transform(word_list).toarray()
print(X)
print(tfidf.vocabulary_)

[[0.         0.         0.         0.27832025 0.         0.42049337
  0.42049337 0.53334252 0.53334252 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.42049337 0.42049337 0.27832025 0.         0.
  0.         0.         0.         0.53334252 0.53334252 0.
  0.         0.         0.        ]
 [0.36141758 0.         0.         0.23921859 0.36141758 0.36141758
  0.36141758 0.         0.         0.         0.         0.45841237
  0.45841237 0.         0.        ]
 [0.36141758 0.36141758 0.36141758 0.23921859 0.36141758 0.
  0.         0.         0.         0.         0.         0.
  0.         0.45841237 0.45841237]]
{'persona': 7, 'like': 5, 'icecream': 3, 'persona like': 8, 'like icecream': 6, 'personb': 9, 'hate': 1, 'personb hate': 10, 'hate icecream': 2, 'personc': 11, 'coffee': 0, 'personc like': 12, 'icecream coffee': 4, 'persond': 13, 'persond hate': 14}


In [25]:
from gensim.models import Word2Vec, KeyedVectors 
import gensim.downloader as api 

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

[==========================------------------------] 53.5% 890.0/1662.8MB downloaded

ContentTooShortError: <urlopen error retrieval incomplete: got only 933232640 out of 1743563840 bytes>