In [1]:
import torch 
import torch.nn as nn 
import numpy as np 
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize 
import nltk

In [2]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [3]:
tokens = word_tokenize(document.lower())

In [4]:
# Find out the unique words in the sentence 
# For each word, assign a number
vocab = {'<unk>': 0}
for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token] = len(vocab)
vocab

{'<unk>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799/month': 29,
 '.': 30,
 'total': 31,
 'duration': 32,
 '?': 33,
 '7': 34,
 'months': 35,
 'so': 36,
 'becomes': 37,
 '799': 38,
 '*': 39,
 '=': 40,
 '5600': 41,
 'approx': 42,
 'syllabus': 43,
 'we': 44,
 'will': 45,
 'be': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 ':': 50,
 'python': 51,
 'fundamentals': 52,
 'libraries': 53,
 'analysis': 54,
 'sql': 55,
 'maths': 56,
 'machine': 57,
 'learning': 58,
 'ml': 59,
 'algorithms': 60,
 'practical': 61,
 'mlops': 62,
 'case': 63,
 'studies': 64,
 'can': 65,
 'check': 66,
 'detailed': 67,
 'here': 68,
 '-': 69,
 'https': 70,
 '//learnwith.campusx.i

In [57]:
# Convert the entire sentence to vocab numbers 
def word_to_num(word):
    if word in vocab:
        return vocab[word]
    else: 
        return vocab['<unk>']
    
word_to_num('mentors')

284

In [6]:
# Convert each word in sentence to unique numbers
input_sentences = document.split('\n')
for i, sentence in enumerate(input_sentences):
    words = word_tokenize(sentence.lower())
    decoded_words = []
    for word in words:
        # print(i, word)
        decoded_words.append(word_to_num(word))
    input_sentences[i] = decoded_words
input_sentences

[[1, 2, 3],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29, 30],
 [4, 5, 2, 31, 32, 27, 2, 6, 33],
 [2,
  31,
  32,
  27,
  2,
  6,
  5,
  34,
  35,
  30,
  36,
  2,
  31,
  6,
  7,
  37,
  38,
  39,
  34,
  40,
  28,
  41,
  12,
  42,
  30,
  15],
 [4, 5, 2, 43, 27, 2, 11, 3, 33],
 [44, 45, 46, 47, 2, 48, 49, 50],
 [51, 52],
 [51, 53, 8, 9, 10],
 [9, 54],
 [55, 8, 9, 10],
 [56, 8, 57, 58],
 [59, 60],
 [61, 59],
 [62],
 [63, 64],
 [22, 65, 66, 2, 67, 43, 68, 69, 70, 50, 71],
 [45, 72, 58, 73, 74, 46, 17, 75, 27, 76, 3, 33],
 [77, 78, 74, 73, 72, 58, 79, 80, 81, 17, 75, 27, 76, 3, 82, 83, 84, 30],
 [4, 85, 86, 87, 17, 88, 89, 33, 45, 86, 90, 17, 91, 27, 2, 89, 33],
 [92,
  93,
  94,
  95,
  80,
  96,
  78,
  36,
  97,
  85,
  22,
  87,
  17,
  89,
  22,
  65,
  98,
  99,
  73,
  100,
  2,
  91,
  30],
 [21, 65, 86, 101, 2, 102, 103, 33],
 [104,
  76,
  105,
  106,
  24,
  107,
  108,
  109,
  108,
  110,
  111,
  27,

In [7]:
# Form sequences 
# [1,2,3] -> [1,2] [1,2,3]
# [3,5,1,2] -> [3,5] [3,5,1] [3,5,1,2]

def form_sequences(numbers):
    limit = len(numbers)
    if limit <= 1:
        return numbers
    sequences = []
    for i in range(1, limit):        
        sequences.append(numbers[:i+1])
    return sequences
form_sequences([3,5,1,2])

[[3, 5], [3, 5, 1], [3, 5, 1, 2]]

In [8]:
training_sequence = []
seq_lengths = []
for sentence in input_sentences:
    seq = form_sequences(sentence)     
    for item in seq:
        if isinstance(item, int):
            print(f"Int type detected: {item}")
            training_sequence.append([item])
            seq_lengths.append(1)  
        else: 
            training_sequence.append(item)
            seq_lengths.append(len(item))  
             
# print(training_sequence[0])

acceptable_len = max(seq_lengths)
acceptable_len


Int type detected: 62
Int type detected: 122


62

In [9]:
# Apply left padding for all inputs to have same size 
padded_training_sequence = []
for i, seq in enumerate(training_sequence):
    padded_training_sequence.append([0] * (acceptable_len - len(seq)) + seq)

print(len(padded_training_sequence[0]), padded_training_sequence[0])
print(len(padded_training_sequence[61]), padded_training_sequence[61])


62 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]
62 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 31, 32, 27, 2, 6, 5, 34, 35, 30, 36, 2, 31, 6, 7, 37, 38, 39, 34, 40, 28, 41, 12]


In [10]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [11]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:, -1]
X,y

(tensor([[  0,   0,   0,  ...,   0,   0,   1],
         [  0,   0,   0,  ...,   0,   1,   2],
         [  0,   0,   0,  ...,   0,   0,   4],
         ...,
         [  0,   0,   0,  ...,   0, 285, 176],
         [  0,   0,   0,  ..., 285, 176, 286],
         [  0,   0,   0,  ..., 176, 286, 287]]),
 tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
          15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
          27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
          27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
          39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
          11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
          10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  62,  64,  65,  66,
           2,  67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,
          75,  27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  

In [12]:
class CustomDataSet(Dataset):
    def __init__(self, X, y):
        self.X = X 
        self.y = y

    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self, index):
        return self.X[index], self.y[index]


In [14]:
dataset = CustomDataSet(X, y)
len(dataset)
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [16]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [38]:
class LSTMModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__() 
        self.embedding = nn.Embedding(vocab_size, 100) 
        self.lstm = nn.LSTM(100, 150, batch_first=True)
        self.fc = nn.Linear(150, vocab_size)

    def forward(self, x):
        embedded = self.embedding(x)
        intermediate_hidden_state, (final_hidden_state, final_cell_state) = self.lstm(embedded)
        output = self.fc(final_hidden_state.squeeze(0))
        return output

In [35]:
# Test code for intuition

# [1, 61]
a = dataset[0][0].unsqueeze(0)

# [1, 61, 100]
embed_layer = nn.Embedding(289, 100) 
b = embed_layer(a)
# print(b.shape)

lstm_layer = nn.LSTM(100, 150, batch_first=True)
# c - hidden states for each time step (batch_size, seq_length, hidden_size)
# d - (hn, cn) hidden state at the last time step, cell state at last time step
c, d = lstm_layer(b)
# print(c.shape, d)
fc_layer = nn.Linear(150, 289)

ht, ct = d
print(ht.shape, ct.shape)

# Send final Ct output to fully connected layer for t=2
# print(ct.squeeze(0).shape)
# ht and ct has (1,1,150), so convert to (1,150) using squeeze
fc_layer(ct.squeeze(0)).shape

torch.Size([1, 1, 150]) torch.Size([1, 1, 150])


torch.Size([1, 289])

In [39]:
model = LSTMModel(len(vocab))

In [40]:
epochs = 50
learning_rate = 0.001 
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [43]:
# Training loop 

for epoch in range(epochs):
    total_loss = 0
    for batch_x, batch_y in dataloader:
        optimizer.zero_grad()
        output = model(batch_x)
        loss = criterion(output, batch_y)
        loss.backward() 
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch: {epoch+1} Loss: {total_loss:.4f}")

Epoch: 1 Loss: 3.3000
Epoch: 2 Loss: 3.3560
Epoch: 3 Loss: 3.3221
Epoch: 4 Loss: 3.5926
Epoch: 5 Loss: 3.2319
Epoch: 6 Loss: 3.3438
Epoch: 7 Loss: 3.2874
Epoch: 8 Loss: 3.2902
Epoch: 9 Loss: 3.4574
Epoch: 10 Loss: 3.2479
Epoch: 11 Loss: 3.4007
Epoch: 12 Loss: 3.2726
Epoch: 13 Loss: 3.3824
Epoch: 14 Loss: 3.4048
Epoch: 15 Loss: 3.3695
Epoch: 16 Loss: 3.2985
Epoch: 17 Loss: 3.2462
Epoch: 18 Loss: 3.2196
Epoch: 19 Loss: 3.2517
Epoch: 20 Loss: 3.2070
Epoch: 21 Loss: 3.2443
Epoch: 22 Loss: 3.1633
Epoch: 23 Loss: 3.2554
Epoch: 24 Loss: 3.2218
Epoch: 25 Loss: 3.0944
Epoch: 26 Loss: 3.4460
Epoch: 27 Loss: 3.3131
Epoch: 28 Loss: 3.2215
Epoch: 29 Loss: 3.1575
Epoch: 30 Loss: 3.2289
Epoch: 31 Loss: 3.1903
Epoch: 32 Loss: 3.1223
Epoch: 33 Loss: 3.0980
Epoch: 34 Loss: 3.1087
Epoch: 35 Loss: 3.1199
Epoch: 36 Loss: 3.1736
Epoch: 37 Loss: 3.1109
Epoch: 38 Loss: 3.1831
Epoch: 39 Loss: 3.1328
Epoch: 40 Loss: 3.1401
Epoch: 41 Loss: 3.1091
Epoch: 42 Loss: 3.1066
Epoch: 43 Loss: 3.0845
Epoch: 44 Loss: 3.07

In [86]:
# Prediction

def prediction(model, vocab, text):

    # Tokenize text 
    tokenized_text = word_tokenize(text.lower())

    # Text to numerical indices 
    numerical_text = []
    for word in tokenized_text:
        numerical_text.append(word_to_num(word))

    # Padding 
    # print(numerical_text)
    padded_text = [0]*(acceptable_len - len(numerical_text)) + numerical_text
    padded_text = torch.tensor(padded_text, dtype=torch.long).unsqueeze(0)
    
    # Send to model 
    output = model(padded_text)

    # Predicted index 
    value, index = torch.max(output, dim=1)
    # print(value, index)
    
    # Merge with text
    text += " " + list(vocab.keys())[index]
    return text

In [ ]:
import time

input_text = "The course follows a"
for i in range(10):
    output_text = prediction(model, vocab, input_text)
    print(output_text)
    input_text = output_text
    time.sleep(1)


The course follows a monthly
The course follows a monthly subscription
The course follows a monthly subscription model
The course follows a monthly subscription model where
