In [47]:
import torch 
print(torch.__version__)

2.7.1+cpu


In [48]:
# torch.cuda.is_available()
torch.zeros(3)

tensor([0., 0., 0.])

In [49]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [50]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(torch.zeros_like(x))
print(torch.ones_like(x))

matrix = torch.rand_like(x, dtype=torch.float32)
print(matrix)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.0816, 0.6195, 0.6664],
        [0.0783, 0.4433, 0.2790]])


In [51]:
print(matrix + 2)
print(matrix ** 2)

tensor([[2.0816, 2.6195, 2.6664],
        [2.0783, 2.4433, 2.2790]])
tensor([[0.0067, 0.3838, 0.4441],
        [0.0061, 0.1965, 0.0778]])


In [52]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 0, 0],
        [2, 2, 1]])
tensor([[0, 1],
        [3, 4],
        [0, 4]])


In [53]:
torch.matmul(f,g)

tensor([[ 0,  3],
        [ 6, 14]])

### AutoGrad

In [54]:
# y = x**2, z = sin (y)     Find dz/dx

x = torch.tensor(3.0, requires_grad=True)
y = x**2
z = torch.sin(y)
print(x, y, z)

tensor(3., requires_grad=True) tensor(9., grad_fn=<PowBackward0>) tensor(0.4121, grad_fn=<SinBackward0>)


In [55]:
z.backward()
x.grad

tensor(-5.4668)

In [56]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
print(x,y,w,b)

tensor(6.7000) tensor(0.) tensor(1., requires_grad=True) tensor(0., requires_grad=True)


In [57]:
z = w * x + b 
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [58]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [59]:
from torch.nn import functional as F
loss = F.binary_cross_entropy(y_pred, y)
print(loss.item())

6.701176166534424


In [60]:
loss.backward() 
print(w.grad, b.grad)

tensor(6.6918) tensor(0.9988)
