In [1]:
import torch 
print(torch.__version__)

2.7.1+cpu


In [6]:
# torch.cuda.is_available()
torch.zeros(3)

tensor([0., 0., 0.])

In [8]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(torch.zeros_like(x))
print(torch.ones_like(x))

matrix = torch.rand_like(x, dtype=torch.float32)
print(matrix)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.0823, 0.2808, 0.9648],
        [0.2040, 0.5343, 0.2313]])


In [16]:
print(matrix + 2)
print(matrix ** 2)

tensor([[2.0823, 2.2808, 2.9648],
        [2.2040, 2.5343, 2.2313]])
tensor([[0.0068, 0.0789, 0.9308],
        [0.0416, 0.2855, 0.0535]])


In [18]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 0, 8],
        [2, 2, 9]])
tensor([[8, 7],
        [9, 7],
        [9, 1]])


In [19]:
torch.matmul(f,g)

tensor([[ 88,  22],
        [115,  37]])

### AutoGrad

In [20]:
# y = x**2, z = sin (y)     Find dz/dx

x = torch.tensor(3.0, requires_grad=True)
y = x**2
z = torch.sin(y)
print(x, y, z)

tensor(3., requires_grad=True) tensor(9., grad_fn=<PowBackward0>) tensor(0.4121, grad_fn=<SinBackward0>)


In [21]:
z.backward()
x.grad

tensor(-5.4668)

In [40]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
print(x,y,w,b)

tensor(6.7000) tensor(0.) tensor(1., requires_grad=True) tensor(0., requires_grad=True)


In [23]:
z = w * x + b 
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [39]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
from torch.nn import functional as F
loss = F.binary_cross_entropy(y_pred, y)
print(loss.item())

In [44]:
loss.backward() 
print(w.grad, b.grad)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.